name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get version
      id: version
      run: echo "VERSION=$(go run bin/lessonmd.go -v | cut -c11-)" >> $GITHUB_OUTPUT
    
    - name: Build Windows 64-bit
      run: |
        mkdir -p dist/windows_64
        env GOOS=windows GOARCH=amd64 go build -o dist/windows_64/lessonmd.exe bin/lessonmd.go
    
    - name: Build macOS Intel
      run: |
        mkdir -p dist/mac_intel
        env GOOS=darwin GOARCH=amd64 go build -o dist/mac_intel/lessonmd bin/lessonmd.go
    
    - name: Build macOS Silicon
      run: |
        mkdir -p dist/mac_silicon
        env GOOS=darwin GOARCH=arm64 go build -o dist/mac_silicon/lessonmd bin/lessonmd.go
    
    - name: Build Linux 64-bit
      run: |
        mkdir -p dist/linux_64
        env GOOS=linux GOARCH=amd64 go build -o dist/linux_64/lessonmd bin/lessonmd.go
    
    - name: Create release archives
      run: |
        cd dist/windows_64 && zip lessonmd_${{ steps.version.outputs.VERSION }}_windows64.zip lessonmd.exe && mv lessonmd_${{ steps.version.outputs.VERSION }}_windows64.zip ../
        cd dist/mac_intel && zip lessonmd_${{ steps.version.outputs.VERSION }}_mac_intel.zip lessonmd && mv lessonmd_${{ steps.version.outputs.VERSION }}_mac_intel.zip ../
        cd dist/mac_silicon && zip lessonmd_${{ steps.version.outputs.VERSION }}_mac_silicon.zip lessonmd && mv lessonmd_${{ steps.version.outputs.VERSION }}_mac_silicon.zip ../
        cd dist/linux_64 && zip lessonmd_${{ steps.version.outputs.VERSION }}_linux64.zip lessonmd && mv lessonmd_${{ steps.version.outputs.VERSION }}_linux64.zip ../
        cd dist/linux_64 && tar -czvf lessonmd_${{ steps.version.outputs.VERSION }}_linux64.tar.gz lessonmd && mv lessonmd_${{ steps.version.outputs.VERSION }}_linux64.tar.gz ../
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/lessonmd_${{ steps.version.outputs.VERSION }}_windows64.zip
          dist/lessonmd_${{ steps.version.outputs.VERSION }}_mac_intel.zip
          dist/lessonmd_${{ steps.version.outputs.VERSION }}_mac_silicon.zip
          dist/lessonmd_${{ steps.version.outputs.VERSION }}_linux64.zip
          dist/lessonmd_${{ steps.version.outputs.VERSION }}_linux64.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}